# @format

name: Create env

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: build others
        env:
          CLASH_DASHBOARD: 'https://github.com/Dreamacro/clash-dashboard.git'
          VERSION: 'latest'
          DIR: 'clash-dashboard'
        run: |
          gh repo create Dreamacro/clash-dashboard || git clone https://github.com/Dreamacro/clash-dashboard.git
          cd ${{ env.DIR }} && pnpm i && pnpm build
          docker build -t clash:lastest ..
