# @format

name: Create env

on:
  push:
    branches: [main]
env:
  version: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: build dist
        env:
          CLASH_DASHBOARD: 'https://github.com/Dreamacro/clash-dashboard.git'
          DIR: 'clash-dashboard'
          GH_TOKEN: ${{ github.token }}
        run: |
          gh repo clone Dreamacro/clash-dashboard
          cd ${{ env.DIR }} && pnpm i && pnpm build
      - name: publish docker images
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_V2 }}
      - name: publish docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clash:${{ env.version }}
